# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(verbose_name='pub_date'),
        ),
    ]
