# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0003_auto_20170627_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technology.Part'),
        ),
    ]
