# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0004_auto_20170627_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='part',
        ),
    ]
