# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0005_remove_blog_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='technology.Part'),
        ),
    ]
