# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0007_auto_20170627_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
